#!/bin/sh
_CONDA_ROOT="//?/C:/Thermo_Scientific/Python/envs/example_env_3104_1_target"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
